"""
Layer 4 Query Scenarios (U001-U015): Simulated chatbot queries.
Each scenario defines a query and what the KB must be able to answer.
"""

QUERY_SCENARIOS = [
    {
        "id": "U001",
        "query": "What Endstar tools do I need for Lesson 5?",
        "required_field": "endstar_tools",
        "scope": {"lesson_id": 5},
        "expect": "non_empty_list",
        "description": "Teacher asks about tools for a specific lesson",
    },
    {
        "id": "U002",
        "query": "Which lessons use the Triggers tool?",
        "required_field": "endstar_tools",
        "scope": {"search_value": "Triggers"},
        "expect": "at_least_one_match",
        "description": "Teacher searches for lessons by tool name",
    },
    {
        "id": "U003",
        "query": "What are the learning objectives for Term 2 Lesson 1?",
        "required_field": "learning_objectives",
        "scope": {"term": 2, "lesson_id": 1},
        "expect": "non_empty_list",
        "description": "Teacher asks for specific lesson objectives",
    },
    {
        "id": "U004",
        "query": "What activities are planned for Term 3 Lesson 6?",
        "required_field": "activity_description",
        "scope": {"term": 3, "lesson_id": 6},
        "expect": "non_empty_string",
        "description": "Teacher asks about lesson activities",
    },
    {
        "id": "U005",
        "query": "How is Lesson 8 assessed?",
        "required_field": "assessment_signals",
        "scope": {"lesson_id": 8},
        "expect": "non_empty_list",
        "description": "Teacher asks about assessment for a lesson",
    },
    {
        "id": "U006",
        "query": "Where can I find the assessment form for Term 1?",
        "required_field": "resources",
        "scope": {"term": 1, "search_value": "form"},
        "expect": "at_least_one_match",
        "description": "Teacher looks for assessment resources",
    },
    {
        "id": "U007",
        "query": "What is Lesson 3 about?",
        "required_field": "lesson_title",
        "scope": {"lesson_id": 3},
        "expect": "non_empty_string",
        "description": "Cross-term disambiguation — Lesson 3 exists in all terms",
    },
    {
        "id": "U008",
        "query": "What is the big question for Term 3 Lesson 4?",
        "required_field": "enriched.big_question",
        "scope": {"term": 3, "lesson_id": 4},
        "expect": "non_empty_string",
        "description": "Teacher asks for enriched content from native docs",
    },
    {
        "id": "U009",
        "query": "Which term covers game testing and feedback?",
        "required_field": "core_topics",
        "scope": {"search_value": "testing"},
        "expect": "at_least_one_match",
        "description": "Teacher searches by topic keyword",
    },
    {
        "id": "U010",
        "query": "What videos are available for Term 2 Lesson 3?",
        "required_field": "videos",
        "scope": {"term": 2, "lesson_id": 3},
        "expect": "field_exists",
        "description": "Teacher asks for video resources",
    },
    {
        "id": "U011",
        "query": "Show me resources for Term 1 Lesson 1",
        "required_field": "resources",
        "scope": {"term": 1, "lesson_id": 1},
        "expect": "non_empty_list",
        "description": "Teacher asks for lesson resources",
    },
    {
        "id": "U012",
        "query": "What are the core topics for Term 2 Lesson 7?",
        "required_field": "core_topics",
        "scope": {"term": 2, "lesson_id": 7},
        "expect": "non_empty_list",
        "description": "Teacher asks for core topics",
    },
    {
        "id": "U013",
        "query": "List all lessons in Term 1",
        "required_field": "lessons",
        "scope": {"term": 1},
        "expect": "lesson_count_matches_profile",
        "description": "Teacher requests full term overview",
    },
    {
        "id": "U014",
        "query": "What keywords describe Term 3 Lesson 5?",
        "required_field": "keywords",
        "scope": {"term": 3, "lesson_id": 5},
        "expect": "non_empty_list",
        "description": "Teacher asks for lesson keywords",
    },
    {
        "id": "U015",
        "query": "What should students do in class for Term 1 Lesson 10?",
        "required_field": "activity_description",
        "scope": {"term": 1, "lesson_id": 10},
        "expect": "non_empty_string",
        "description": "Teacher asks for classroom activity details",
    },
]
